apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hemanthreddy-22/CI-CD-End-To-End.git
    targetRevision: main
    path: java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
